version: 2
updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    groups:
      weekly-nonbreaking:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
